import "~/styles/globals.css";

import { DM_Sans } from "next/font/google";
import { type Metadata } from "next";

const dm_sans = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${dm_sans.className}`}>
      <body>{children}</body>
    </html>
  );
}
